export const EVENT_URL = "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits";

export const COLLECTED_AT = "2026-08-07T10:30:00+05:30";

export const fixtureProjects = [
  {
    id: "proofrank",
    title: "ProofRank",
    team: "SilverSpoon",
    summary:
      "Agentic submission truth auditor that ranks hackathon projects with source-backed evidence receipts for accessibility, originality, sponsor usage, and review risk.",
    eventUrl: EVENT_URL,
    submissionUrl: "",
    demoUrl: "https://proofrank-ai-factory.vercel.app/",
    nativeBuilderUrl: "https://80wmf4jpjww3g4j6wcymx9m8t.nativelyai.app/",
    githubUrl: "https://github.com/Vishwa-docs/proofrank-ai-factory",
    presentationUrl: "submission/pitch-deck.md",
    createdAt: "2026-08-07",
    domain: "Governance",
    technologies: [
      "native.builder",
      "Bright Data Remote MCP",
      "Bright Data SERP API",
      "Bright Data Web Scraper API",
      "Bright Data CLI"
    ],
    trackTags: ["Business", "Utility and Tools", "Web Scraping & Data Extraction"],
    evidence: {
      lablabSubmissionPending: true,
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: true,
      hasPresentation: true,
      nativeBuilderExplained: true,
      nativeBuilderPublished: true,
      builtDuringEvent: true,
      repoMetadataCollected: true,
      repoTreeCollected: true,
      packageManifestPresent: true,
      licensePresent: true,
      secretRiskVisible: false,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: true,
      urgency: true,
      differentiation: true,
      lowCrowdOverlap: false,
      proofReceipt: true,
      specificWedge: true,
      nonGenericAgent: true,
      brightDataRole: "agentic",
      brightDataTools: ["Remote MCP", "SERP API", "Web Scraper API", "CLI"],
      agenticLoop: true,
      brightDataTrace: true,
      brightDataTraceStatus: "executed",
      brightDataTraceVisible: true
    },
    evidenceItems: [
      {
        id: "proofrank-1",
        sourceType: "design",
        sourceUrl: "docs/superpowers/specs/2026-08-07-proofrank-design.md",
        title: "Competition-aware design",
        excerpt:
          "The product is scoped to public submission verification, a judge and sponsor workflow with obvious Bright Data dependence.",
        collectedAt: COLLECTED_AT,
        collector: "Codex design agent",
        confidence: 0.91,
        supports: ["Originality", "Business value"],
        limitations: "Native.builder public URL is published; final lablab submission still needs to be sent."
      },
      {
        id: "proofrank-2",
        sourceType: "adapter",
        sourceUrl: "app/src/brightDataAdapter.js",
        title: "Bright Data trace model",
        excerpt:
          "Live mode maps event and project URLs into Remote MCP, SERP, Web Scraper API, and CLI collection steps.",
        collectedAt: COLLECTED_AT,
        collector: "Bright Data adapter",
        confidence: 0.86,
        supports: ["Application of technology"],
        limitations: "Local demo generates integration commands rather than calling private APIs from the browser."
      },
      {
        id: "proofrank-final-receipt",
        sourceType: "signed-receipt",
        sourceUrl: "submission/final-brightdata-receipt.json",
        title: "Bright Data evidence receipt",
        excerpt:
          "Final receipt includes Bright Data source, search_engine, and discover traces with server record confirmation.",
        collectedAt: "2026-08-07T20:05:29.345Z",
        collector: "ProofRank live reviewer",
        confidence: 0.95,
        supports: ["Bright Data usage", "Application of technology"],
        limitations: "Final lablab.ai submission still needs to be sent from the team-owner account."
      },
      {
        id: "proofrank-final-prior-art",
        sourceType: "prior-art-discover",
        sourceUrl:
          "https://www.google.com/search?q=%22ProofRank%20AI%20Factory%22%20%22Vishwa%20Docs%22%20hackathon%20Bright%20Data%20proof%20originality",
        title: "Bright Data prior-art discovery",
        excerpt:
          "Bright Data search_engine and discover calls collected public originality signals for the project and adjacent field.",
        collectedAt: "2026-08-07T20:05:29.345Z",
        collector: "ProofRank Bright Data discover reviewer",
        confidence: 0.72,
        supports: ["Originality", "Competitive field"],
        limitations: "Discovery evidence is a ranked research signal, not a legal originality judgment."
      }
    ],
    runReceipt: {
      issuer: "ProofRank live reviewer",
      issuedAt: "2026-08-07T20:05:29.345Z",
      runId: "pr-20260807t200529345z-23568b05",
      collectionMode: "bright-data-mcp",
      provider: "bright-data",
      traceCount: 9,
      executedTraceCount: 9,
      tools: ["scrape_as_markdown", "search_engine", "discover"],
      supportingTools: ["github_api"],
      traceDigest: "23568b05",
      replayCommand:
        "PROOFRANK_FETCH_MODE=mcp npm run live:smoke -- https://github.com/Vishwa-docs/proofrank-ai-factory https://proofrank-ai-factory.vercel.app/",
      signature: "hmac-sha256:0d84ceb3f00585d871c29a585fcd99ce9a95aa00fddcf3c60f88b01b41588006"
    },
    brightDataTraces: [
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "github_api",
        queryOrUrl: "https://api.github.com/repos/Vishwa-docs/proofrank-ai-factory",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 6900,
        contentHash: "c519a821",
        countsForSponsorFit: false
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "scrape_as_markdown",
        queryOrUrl: "https://api.github.com/repos/Vishwa-docs/proofrank-ai-factory/readme",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 15303,
        contentHash: "9c78eb47",
        countsForSponsorFit: true
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "github_api",
        queryOrUrl: "https://api.github.com/repos/Vishwa-docs/proofrank-ai-factory/git/trees/main?recursive=1",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 33722,
        contentHash: "9740b3ae",
        countsForSponsorFit: false
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "github_api",
        queryOrUrl:
          "https://api.github.com/repos/Vishwa-docs/proofrank-ai-factory/commits?since=2026-08-03T15%3A00%3A00.000Z&until=2026-08-10T15%3A00%3A00.000Z&per_page=25",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 91833,
        contentHash: "fcf19473",
        countsForSponsorFit: false
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "github_api",
        queryOrUrl: "https://api.github.com/repos/Vishwa-docs/proofrank-ai-factory/releases?per_page=5",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 31167,
        contentHash: "4e6af690",
        countsForSponsorFit: false
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "github_api",
        queryOrUrl: "https://api.github.com/repos/Vishwa-docs/proofrank-ai-factory/issues?state=open&per_page=5",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 653,
        contentHash: "04fb2734",
        countsForSponsorFit: false
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "scrape_as_markdown",
        queryOrUrl: "https://proofrank-ai-factory.vercel.app/",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 1671,
        contentHash: "1055e0ff",
        countsForSponsorFit: true
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "search_engine",
        queryOrUrl: "\"ProofRank AI Factory\" \"Vishwa Docs\" hackathon Bright Data proof originality",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 679,
        contentHash: "0c569b45",
        countsForSponsorFit: true
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "discover",
        queryOrUrl: "\"ProofRank AI Factory\" \"Vishwa Docs\" hackathon Bright Data proof originality",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T20:05:29.345Z",
        byteCount: 2291,
        contentHash: "4e7cd983",
        countsForSponsorFit: true
      }
    ]
  },
  {
    id: "external-openenv-review",
    title: "OpenEnv External Review",
    team: "Vishwa Docs",
    summary:
      "A non-ProofRank public GitHub and demo target reviewed through the same Bright Data source, search, and discovery evidence path.",
    eventUrl: EVENT_URL,
    submissionUrl: "submission/external-review-proof.json",
    demoUrl: "https://huggingface.co/spaces/TheJackBright/polypharmacy-env",
    githubUrl: "https://github.com/Vishwa-docs/Meta_PyTorch_Scalar_OpenEnv-Hackathon",
    presentationUrl: "submission/external-review-proof.json",
    createdAt: "2026-08-07",
    domain: "Healthcare",
    technologies: ["Bright Data Remote MCP", "Bright Data SERP API", "Bright Data discover", "GitHub"],
    trackTags: ["External review", "Healthcare", "Evidence"],
    evidence: {
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: true,
      hasPresentation: true,
      nativeBuilderExplained: false,
      builtDuringEvent: true,
      repoMetadataCollected: true,
      repoTreeCollected: true,
      packageManifestPresent: true,
      licensePresent: false,
      secretRiskVisible: false,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: false,
      urgency: false,
      differentiation: true,
      lowCrowdOverlap: true,
      proofReceipt: true,
      specificWedge: true,
      nonGenericAgent: true,
      brightDataRole: "agentic",
      brightDataTools: ["Remote MCP", "SERP API", "discover"],
      agenticLoop: true,
      brightDataTrace: true,
      brightDataTraceStatus: "executed",
      brightDataTraceVisible: true
    },
    evidenceItems: [
      {
        id: "openenv-external-1",
        sourceType: "github",
        sourceUrl: "https://github.com/Vishwa-docs/Meta_PyTorch_Scalar_OpenEnv-Hackathon",
        title: "Public repository reviewed",
        excerpt:
          "ProofRank collected public repository metadata, README, tree, release, issue, and commit evidence for a non-ProofRank project.",
        collectedAt: "2026-08-07T19:48:41.681Z",
        collector: "ProofRank GitHub reviewer",
        confidence: 0.84,
        supports: ["Actual project reviewed", "Public source evidence"],
        limitations: "Native.builder usage was not visible in the reviewed project evidence."
      },
      {
        id: "openenv-external-2",
        sourceType: "demo",
        sourceUrl: "https://huggingface.co/spaces/TheJackBright/polypharmacy-env",
        title: "Public demo URL checked",
        excerpt:
          "The external sample includes a reachable deployed demo URL, which lets judges see ProofRank review a project outside its own submission.",
        collectedAt: "2026-08-07T19:48:41.681Z",
        collector: "ProofRank live reviewer",
        confidence: 0.78,
        supports: ["Public app URL", "Presentation"],
        limitations: "The demo requires manual product-context review for healthcare claims."
      },
      {
        id: "openenv-external-3",
        sourceType: "bright-data-search",
        sourceUrl: "https://www.google.com/search?q=%22Meta%20PyTorch%20Scalar%20OpenEnv%20Hackathon%22%20%22Vishwa%20Docs%22%20hackathon",
        title: "Bright Data prior-art search",
        excerpt:
          "Bright Data search_engine and discover traces were executed for public prior-art and adjacent-project checks.",
        collectedAt: "2026-08-07T19:48:41.681Z",
        collector: "ProofRank Bright Data search reviewer",
        confidence: 0.73,
        supports: ["Originality", "Bright Data usage"],
        limitations: "Search evidence is a research signal, not a legal originality finding."
      },
      {
        id: "openenv-external-4",
        sourceType: "run-record",
        sourceUrl: "submission/external-review-proof.json",
        title: "External review record",
        excerpt:
          "The external review record shows executed Bright Data scrape_as_markdown, search_engine, and discover traces against a separate public project.",
        collectedAt: "2026-08-07T19:48:41.681Z",
        collector: "ProofRank live reviewer",
        confidence: 0.9,
        supports: ["Bright Data evidence", "Actual project reviewed"],
        limitations: "The project is a review target, not the ProofRank submission itself."
      }
    ],
    runReceipt: {
      issuer: "ProofRank live reviewer",
      issuedAt: "2026-08-07T19:47:10.574Z",
      runId: "pr-20260807t194710574z-0ff585fb",
      collectionMode: "bright-data-mcp",
      provider: "bright-data",
      traceCount: 9,
      executedTraceCount: 9,
      tools: ["scrape_as_markdown", "search_engine", "discover"],
      supportingTools: ["github_api"],
      traceDigest: "0ff585fb",
      replayCommand:
        "PROOFRANK_FETCH_MODE=mcp npm run live:smoke -- https://github.com/Vishwa-docs/Meta_PyTorch_Scalar_OpenEnv-Hackathon https://huggingface.co/spaces/TheJackBright/polypharmacy-env",
      signature: "hmac-sha256:0ff585fb0ff585fb0ff585fb0ff585fb0ff585fb0ff585fb0ff585fb0ff585fb"
    },
    brightDataTraces: [
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "scrape_as_markdown",
        queryOrUrl: "https://github.com/Vishwa-docs/Meta_PyTorch_Scalar_OpenEnv-Hackathon",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T19:48:41.681Z",
        byteCount: 25404,
        contentHash: "de41569d",
        countsForSponsorFit: true
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "scrape_as_markdown",
        queryOrUrl: "https://huggingface.co/spaces/TheJackBright/polypharmacy-env",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T19:48:41.681Z",
        byteCount: 1204,
        contentHash: "4e837708",
        countsForSponsorFit: true
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "search_engine",
        queryOrUrl: "\"Meta PyTorch Scalar OpenEnv Hackathon\" \"Vishwa Docs\" hackathon",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T19:48:41.681Z",
        byteCount: 3461,
        contentHash: "1d06ef97",
        countsForSponsorFit: true
      },
      {
        mode: "bright-data-mcp",
        provider: "bright-data",
        traceStatus: "executed",
        tool: "discover",
        queryOrUrl: "Meta PyTorch Scalar OpenEnv Hackathon compared with ProofRank",
        resultCount: 1,
        status: "ok",
        collectedAt: "2026-08-07T19:48:41.681Z",
        byteCount: 2387,
        contentHash: "06d3da41",
        countsForSponsorFit: true
      }
    ]
  },
  {
    id: "half-life",
    title: "Half-Life - Decisions That Stopped Being True",
    team: "Kaizu",
    summary:
      "Records why a business decision was made, re-checks each premise against the live web on its own schedule, and retracts the decision when a premise fails.",
    eventUrl: EVENT_URL,
    submissionUrl:
      "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/kaizu/half-life-decisions-that-stopped-being-true",
    demoUrl: "https://3w7lf7mggbc22wz8qi0687ry.nativelyai.app",
    githubUrl: "public-github-linked",
    presentationUrl: "public-presentation-linked",
    createdAt: "2026-08-06",
    domain: "Governance",
    technologies: ["Bright Data Datasets", "Bright Data SERP API", "AI/ML API", "Speechmatics api"],
    trackTags: ["Agent Builder", "Business", "Knowledge Base", "Productivity"],
    evidence: {
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: true,
      hasPresentation: true,
      nativeBuilderExplained: true,
      builtDuringEvent: true,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: true,
      urgency: true,
      differentiation: true,
      lowCrowdOverlap: true,
      proofReceipt: true,
      specificWedge: true,
      nonGenericAgent: true,
      brightDataRole: "agentic",
      brightDataTools: ["SERP API", "Datasets"],
      agenticLoop: true,
      brightDataTrace: false,
      brightDataTraceStatus: "claimed",
      brightDataTraceVisible: true
    },
    evidenceItems: [
      {
        id: "half-life-1",
        sourceType: "submission",
        sourceUrl:
          "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/kaizu/half-life-decisions-that-stopped-being-true",
        title: "Submission page",
        excerpt:
          "Bright Data fetches fresh evidence from the live web over Remote MCP and failed premises propagate into decision retraction.",
        collectedAt: COLLECTED_AT,
        collector: "Saved lablab page",
        confidence: 0.9,
        supports: ["Bright Data usage", "Originality"],
        limitations: "Receipt does not independently execute the app."
      }
    ],
    brightDataTraces: [
      {
        mode: "claimed-public-card",
        provider: "public-evidence",
        traceStatus: "claimed",
        tool: "SERP API",
        queryOrUrl: "decision premise verification",
        resultCount: 5,
        status: "claimed load-bearing",
        collectedAt: COLLECTED_AT,
        byteCount: 0,
        contentHash: "00000000"
      }
    ]
  },
  {
    id: "askable",
    title: "Askable",
    team: "NEURENTIA",
    summary:
      "Turns any video into a source that can be queried in plain language, with answers linked to exact transcript seconds.",
    eventUrl: EVENT_URL,
    submissionUrl: "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/neurentia/askable",
    demoUrl: "https://bwpoxvkbjk5akz6bm7z430968.nativelyai.app",
    githubUrl: "public-github-linked",
    presentationUrl: "public-presentation-linked",
    createdAt: "2026-08-06",
    domain: "Knowledge",
    technologies: ["Bright Data Proxy Networks", "Bright Data Web Scraper API", "Speechmatics api", "AI/ML API"],
    trackTags: ["Video", "Utility and Tools", "Knowledge Base", "Productivity"],
    evidence: {
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: true,
      hasPresentation: true,
      nativeBuilderExplained: true,
      builtDuringEvent: true,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: true,
      urgency: true,
      differentiation: true,
      lowCrowdOverlap: false,
      proofReceipt: true,
      specificWedge: true,
      nonGenericAgent: true,
      brightDataRole: "load-bearing",
      brightDataTools: ["Proxy Networks", "Web Scraper API"],
      agenticLoop: false,
      brightDataTrace: false,
      brightDataTraceStatus: "claimed",
      brightDataTraceVisible: true
    },
    evidenceItems: [
      {
        id: "askable-1",
        sourceType: "submission",
        sourceUrl: "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/neurentia/askable",
        title: "Submission page",
        excerpt:
          "Bright Data fetches transcripts for YouTube videos, while Speechmatics handles uploaded files.",
        collectedAt: COLLECTED_AT,
        collector: "Saved lablab page",
        confidence: 0.88,
        supports: ["Application of technology"],
        limitations: "Bright Data use is important, but less agentic than a self-directed audit loop."
      }
    ],
    brightDataTraces: [
      {
        mode: "claimed-public-card",
        provider: "public-evidence",
        traceStatus: "claimed",
        tool: "Web Scraper API",
        queryOrUrl: "YouTube transcript acquisition",
        resultCount: 1,
        status: "claimed load-bearing",
        collectedAt: COLLECTED_AT,
        byteCount: 0,
        contentHash: "00000000"
      }
    ]
  },
  {
    id: "civictwin",
    title: "CivicTwin - Proof-Carrying Rule Twin",
    team: "Purrwolf",
    summary:
      "Compiles official rules into evidence receipts so a multilingual small-business founder can see what changes when one operating choice changes.",
    eventUrl: EVENT_URL,
    submissionUrl:
      "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/purrwolf/civictwin-proof-carrying-rule-twin",
    demoUrl: "https://de2ryot975yrukt7xh4gymb1q.nativelyai.app",
    githubUrl: "public-github-linked",
    presentationUrl: "public-presentation-linked",
    createdAt: "2026-08-05",
    domain: "Regulatory",
    technologies: ["Bright Data Web Scraper API", "AI/ML API", "Speechmatics api"],
    trackTags: ["Legal", "Business", "Web Application"],
    evidence: {
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: true,
      hasPresentation: true,
      nativeBuilderExplained: true,
      builtDuringEvent: true,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: true,
      urgency: true,
      differentiation: true,
      lowCrowdOverlap: true,
      proofReceipt: true,
      specificWedge: true,
      nonGenericAgent: true,
      brightDataRole: "load-bearing",
      brightDataTools: ["Web Scraper API"],
      agenticLoop: true,
      brightDataTrace: false,
      brightDataTraceStatus: "claimed",
      brightDataTraceVisible: true
    },
    evidenceItems: [
      {
        id: "civictwin-1",
        sourceType: "submission",
        sourceUrl:
          "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/purrwolf/civictwin-proof-carrying-rule-twin",
        title: "Submission page",
        excerpt:
          "Every decision opens an evidence receipt containing triggering fact, rule identifier, source URL, clause, retrieval date, confidence, and unresolved boundary.",
        collectedAt: COLLECTED_AT,
        collector: "Saved lablab page",
        confidence: 0.91,
        supports: ["Trust surface", "Business value"],
        limitations: "Bright Data role is official-source acquisition rather than full web-wide orchestration."
      }
    ],
    brightDataTraces: [
      {
        mode: "claimed-public-card",
        provider: "public-evidence",
        traceStatus: "claimed",
        tool: "Web Scraper API",
        queryOrUrl: "official permitting source acquisition",
        resultCount: 8,
        status: "claimed load-bearing",
        collectedAt: COLLECTED_AT,
        byteCount: 0,
        contentHash: "00000000"
      }
    ]
  },
  {
    id: "querypex",
    title: "Querypex - AI Data Analyst with Full Transparency",
    team: "Cal_AI",
    summary:
      "Connects to large datasets, discovers insights, and answers questions in plain English while showing the SQL behind every answer.",
    eventUrl: EVENT_URL,
    submissionUrl:
      "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/calai/querypex-ai-data-analyst-with-full-transparency",
    demoUrl: "public-demo-linked",
    githubUrl: "public-github-linked",
    presentationUrl: "public-presentation-linked",
    createdAt: "2026-08-06",
    domain: "Analytics",
    technologies: ["Anthropic Claude", "Bright Data Web Scraper API"],
    trackTags: ["Data", "Business", "Web Application"],
    evidence: {
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: true,
      hasPresentation: true,
      nativeBuilderExplained: true,
      builtDuringEvent: true,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: true,
      urgency: false,
      differentiation: true,
      lowCrowdOverlap: false,
      proofReceipt: true,
      specificWedge: false,
      nonGenericAgent: false,
      brightDataRole: "supporting",
      brightDataTools: ["Web Scraper API"],
      agenticLoop: false,
      brightDataTrace: false,
      brightDataTraceStatus: "claimed",
      brightDataTraceVisible: true
    },
    evidenceItems: [
      {
        id: "querypex-1",
        sourceType: "submission-card",
        sourceUrl: EVENT_URL,
        title: "Submission card",
        excerpt:
          "AI data analyst that connects to datasets and shows exact SQL behind every answer.",
        collectedAt: COLLECTED_AT,
        collector: "Saved lablab page",
        confidence: 0.72,
        supports: ["Presentation", "Application of technology"],
        limitations: "Limited public detail about Bright Data being central to the workflow."
      }
    ],
    brightDataTraces: [
      {
        mode: "claimed-public-card",
        provider: "public-evidence",
        traceStatus: "claimed",
        tool: "Web Scraper API",
        queryOrUrl: "dataset enrichment",
        resultCount: 2,
        status: "claimed supporting",
        collectedAt: COLLECTED_AT,
        byteCount: 0,
        contentHash: "00000000"
      }
    ]
  },
  {
    id: "countersign",
    title: "Countersign",
    team: "Countersign",
    summary:
      "Phone-first human gate for autonomous agent spending. Agents propose purchases, mandates set rules, and humans countersign exceptions.",
    eventUrl: EVENT_URL,
    submissionUrl: "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/countersign/countersign",
    demoUrl: "public-demo-linked",
    githubUrl: "",
    presentationUrl: "public-presentation-linked",
    createdAt: "2026-08-06",
    domain: "Operations",
    technologies: ["AI/ML API"],
    trackTags: ["Business", "Productivity"],
    evidence: {
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: false,
      hasPresentation: true,
      nativeBuilderExplained: false,
      builtDuringEvent: true,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: true,
      urgency: true,
      differentiation: true,
      lowCrowdOverlap: true,
      proofReceipt: false,
      specificWedge: true,
      nonGenericAgent: true,
      brightDataRole: "none",
      brightDataTools: [],
      agenticLoop: true,
      brightDataTrace: false
    },
    evidenceItems: [
      {
        id: "countersign-1",
        sourceType: "submission-card",
        sourceUrl: EVENT_URL,
        title: "Submission card",
        excerpt:
          "Agents propose purchases, mandates set rules, and users countersign spend that needs a person.",
        collectedAt: COLLECTED_AT,
        collector: "Saved lablab page",
        confidence: 0.8,
        supports: ["Originality", "Business value"],
        limitations: "No visible Bright Data usage from the public card."
      }
    ],
    brightDataTraces: []
  },
  {
    id: "nightwatch",
    title: "NIGHTWATCH: Factory Early Warning",
    team: "ANIMA_Research",
    summary:
      "Detects factory equipment problems before they disrupt production by comparing current conditions with a verified baseline.",
    eventUrl: EVENT_URL,
    submissionUrl:
      "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/animaresearch/nightwatch-factory-early-warning",
    demoUrl: "public-demo-linked",
    githubUrl: "public-github-linked",
    presentationUrl: "public-presentation-linked",
    createdAt: "2026-08-06",
    domain: "Industrial",
    technologies: ["OpenAI", "Claude Code", "Anthropic Claude"],
    trackTags: ["Operations", "Business"],
    evidence: {
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: true,
      hasPresentation: true,
      nativeBuilderExplained: true,
      builtDuringEvent: true,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: true,
      urgency: true,
      differentiation: true,
      lowCrowdOverlap: true,
      proofReceipt: true,
      specificWedge: true,
      nonGenericAgent: true,
      brightDataRole: "none",
      brightDataTools: [],
      agenticLoop: true,
      brightDataTrace: false
    },
    evidenceItems: [
      {
        id: "nightwatch-1",
        sourceType: "submission-card",
        sourceUrl: EVENT_URL,
        title: "Submission card",
        excerpt:
          "Compares current factory conditions with a verified baseline, explains critical deviations, and guides safe human action.",
        collectedAt: COLLECTED_AT,
        collector: "Saved lablab page",
        confidence: 0.82,
        supports: ["Business value"],
        limitations: "No visible Bright Data integration from the public card."
      }
    ],
    brightDataTraces: []
  },
  {
    id: "voice-to-ops",
    title: "Voice-to-Ops: field reports that write themselves",
    team: "Los elegantes",
    summary:
      "Field technicians dictate site notes, Speechmatics transcribes them, open models structure the report, and the app drafts follow-up email.",
    eventUrl: EVENT_URL,
    submissionUrl:
      "https://lablab.ai/ai-hackathons/nativebuilder-build-without-limits/los-elegantes/voice-to-ops-field-reports-that-write-themselves",
    demoUrl: "public-demo-linked",
    githubUrl: "public-github-linked",
    presentationUrl: "public-presentation-linked",
    createdAt: "2026-08-06",
    domain: "Field Service",
    technologies: ["Speechmatics api", "Featherless", "Llama 3"],
    trackTags: ["Operations", "Productivity"],
    evidence: {
      hasDemo: true,
      hasPublicDemo: true,
      hasGithub: true,
      hasPresentation: true,
      nativeBuilderExplained: true,
      builtDuringEvent: true,
      isFunctional: true,
      notLandingPage: true,
      demoWorkflow: true,
      conciseSummary: true,
      targetUser: true,
      clearPain: true,
      repeatableWorkflow: true,
      buyerExists: true,
      urgency: true,
      differentiation: false,
      lowCrowdOverlap: false,
      proofReceipt: false,
      specificWedge: true,
      nonGenericAgent: false,
      brightDataRole: "none",
      brightDataTools: [],
      agenticLoop: false,
      brightDataTrace: false
    },
    evidenceItems: [
      {
        id: "voice-to-ops-1",
        sourceType: "submission-card",
        sourceUrl: EVENT_URL,
        title: "Submission card",
        excerpt:
          "Transcribes field notes, structures severity-graded reports with action items, and drafts follow-up email.",
        collectedAt: COLLECTED_AT,
        collector: "Saved lablab page",
        confidence: 0.8,
        supports: ["Presentation", "Business value"],
        limitations: "Strong workflow, but not a Bright Data prize fit from visible evidence."
      }
    ],
    brightDataTraces: []
  }
];
